// web3 is an Ethereum client library
import Web3 from "web3";
const web3 = new Web3();

web3.setProvider(new web3.providers.WebsocketProvider('ws://localhost:7545'));

// This file is generated by the Solidity compiler to easily interact with
// the contract using the web3 library.
import MyToken from './contracts/MyToken.json';

const MyTokenAbi = MyToken.abi;
const MyTokenContract = new web3.eth.Contract(MyTokenAbi, '0x9D52A5C114662a0D07F6a0b3820d5e624a3f345B');

export default MyTokenContract;